<?php
/**
 *
 */
    $inputs= $block->getFieldsValue();
?>
<h2><?= __("Add New Brand") ?></h2>

<form class="form" action="<?php echo $block->getFormAction() ?>" method="post" data-mage-init='{"validation":{}}' data-hasrequired="* Required Fields">
    <fieldset class="fieldset">
        <div class="field name required">
            <label class="label" for="brandname"><span> <?= __("Brand Name") ?></span></label>
            <div class="control">
                <input name="brandname" id="brandname" title="Brand name"
                       value="<?= $inputs['brandname'] ?? '' ?>" class="input-text" type="text"
                       data-validate='{"required":true}' />
            </div>
        </div>
        <div class="field text required">
            <label class="label" for="brandemail"><span> <?= __("Brand Email") ?></span></label>
            <div class="control">
                <input name="brandemail" id="brandemail" title="Brand email"
                       value="<?= $inputs['brandemail']?? '' ?>" class="input-text" type="email"
                       data-validate='{"required":true}'/>
            </div>
        </div>
        <div class="field text required">
            <label class="label" for="siteurl"><span> <?= __("Official Website") ?></span></label>
            <div class="control">
                <input name="siteurl" id="siteurl" title="Brand Website"
                       value="<?= $inputs['siteurl'] ?? ''?>" class="input-text" type="url"
                       data-validate='{"required":true}'/>
            </div>
        </div>
        <div class="field text required">
            <label class="label" for="decription"><span> <?= __("Brand Description") ?></span></label>
            <div class="control">
                <textarea name="decription" id="decription" title="Brand website"
                          value="" class="input-text" type="text"
                          data-validate='{"required":true ,"min-words":3}'>
                    <?= $inputs['decription'] ?? ''?>
                </textarea>
            </div>
        </div>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span> <?= __("Add Brand") ?></span>
            </button>
        </div>
    </div>

</form>